import time
import sys

print"""
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XFINITY (69.255.234.94)...
Selecting best server based on latency...
Hosted by Shentel Service Company (Ashburn, VA) [20.34 km]: 23.162 ms
Testing download speed........................................
Download: 88.64 Mbit/s
Testing upload speed..................................................
Upload: 5.88 Mbit/s
"""
sys.stdout.flush()
time.sleep(2)
