function [fitresult, gof] = curvefit(time, healthy, unhealthy)
%CREATEFITS(TIME,HEALTHY,UNHEALTHY)
%  Create fits.
%
%  Data for 'healthy' fit:
%      X Input : time
%      Y Output: healthy
%  Data for 'osteoperosis' fit:
%      X Input : time
%      Y Output: unhealthy
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Nov-2014 23:51:44

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'healthy'.
[xData, yData] = prepareCurveData( time, healthy );

% Set up fittype and options.
ft = fittype( 'A*(1/Y+(1/(X+Y)-(1/Y))*exp((-X*Y)/(u*(X+Y))*time))', 'independent', 'time', 'dependent', 'healthy' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-1.5 -1.5 -1.5 -1.5];
opts.StartPoint = [0.568823660872193 0.262971284540144 0.654079098476782 0.528533135506213];
opts.Upper = [0 50000 10000 50000];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'healthy' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'healthy vs. time', 'healthy', 'Location', 'NorthEast' );
% Label axes
xlabel( 'time' );
ylabel( 'healthy' );
grid on

%% Fit: 'osteoperosis'.
[xData, yData] = prepareCurveData( time, unhealthy );

% Set up fittype and options.
ft = fittype( 'A*(1/Y+(1/(X+Y)-(1/Y))*exp((-X*Y)/(u*(X+Y))*time))', 'independent', 'time', 'dependent', 'unhealthy' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-1.5 -100 -10 -100];
opts.StartPoint = [0.469390641058206 0.689214503140008 0.748151592823709 0.162182308193243];
opts.Upper = [5 10 10 100];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'osteoperosis' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'unhealthy vs. time', 'osteoperosis', 'Location', 'NorthEast' );
% Label axes
xlabel( 'time' );
ylabel( 'unhealthy' );
grid on


