// Meteor.publish('DailyBikeDataPub', function(group) {
//   if (Roles.userIsInRole(this.userId, ['Admin', 'Root'], group)) {
//     return DailyBikeData.find();
//   } else {
//     this.stop();
//   }
// });
//
// // ---
// // generated by coffee-script 1.9.2
