function [fitresult, gof] = createFits(t, Healthy, Ostheo)
%CREATEFITS(T,HEALTHY,OSTHEO)
%  Create fits.
%
%  Data for 'HealthyFit' fit:
%      X Input : t
%      Y Output: Healthy
%  Data for 'OstheoFit' fit:
%      X Input : t
%      Y Output: Ostheo
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

  %  Auto-generated by MATLAB on 21-Nov-2014 06:56:02

  %% Initialization.

  % Initialize arrays to store fits and goodness-of-fit.
  fitresult = cell( 2, 1 );
  gof = struct( 'sse', cell( 2, 1 ), ...
      'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

  %% Fit: 'HealthyFit'.
  [xData, yData] = prepareCurveData( t, Healthy );

  % Set up fittype and options.
  ft = fittype( '[-2/(1.16*3.65)]*(1/B+(1/(A+B)-(1/B))*exp((-A*B)/(u*(A+B))*t))', 'independent', 't', 'dependent', 'y' );
  opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
  opts.Display = 'Off';
  opts.Robust = 'Bisquare';
  opts.StartPoint = [0.01 0.5 0.03];

  % Fit model to data.
  [fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

  % % Plot fit with data.
  % figure( 'Name', 'HealthyFit' );
  % h = plot( fitresult{1}, xData, yData );
  % legend( h, 'Healthy vs. t', 'HealthyFit', 'Location', 'NorthEast' );
  % % Label axes
  % xlabel t
  % ylabel Healthy
  % grid on

  %% Fit: 'OstheoFit'.
  [xData, yData] = prepareCurveData( t, Ostheo );

  % Set up fittype and options.
  ft = fittype( '[-2/(1.32*3.79)]*(1/B+(1/(A+B)-(1/B))*exp((-A*B)/(u*(A+B))*t))', 'independent', 't', 'dependent', 'y' );
  opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
  opts.Display = 'Off';
  opts.Robust = 'Bisquare';
  opts.StartPoint = [0.823457828327293 0.694828622975817 0.3171];

  % Fit model to data.
  [fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

  % Plot fit with data.
  % figure( 'Name', 'OstheoFit' );
  % h = plot( fitresult{2}, xData, yData );
  % legend( h, 'Ostheo vs. t', 'OstheoFit', 'Location', 'NorthEast' );
  % % Label axes
  % xlabel t
  % ylabel Ostheo
  % grid on
end