// var BikeData, now, ref, today;
//
// if (DailyBikeData.find().count() !== 0) {
//   if (AvailableBikeLocations.find().count() === 0) {
//     ref = CurrentDay(), today = ref[0], now = ref[1];
//     BikeData = DailyBikeData.find({
//       Day: today,
//       Tag: 'Available'
//     }).fetch();
//     _.each(BikeData, function(BikeDatum) {
//       return AvailableBikeLocations.insert({
//         Bike: BikeDatum.Bike,
//         Day: BikeDatum.Day,
//         Tag: ['Available'],
//         Positions: {
//           Timestamp: BikeDatum.Positions[1].Timestamp,
//           Lat: BikeDatum.Positions[1].Lat,
//           Lng: BikeDatum.Positions[1].Lng
//         }
//       });
//     });
//     console.log('Created AvailableBikeLocations data schema');
//   }
// }
//
// // ---
// // generated by coffee-script 1.9.2
