// var Position, blank, countTime, i, namePoint, now, randGPS, randGPSPoint, randNames, randomNow, ref, today;
//
// randNames = ['Anastasia Romanoff', 'Marie Antoinette', 'Chuff Chuffington', 'Kate Middleton', 'Harry Potter', 'Snow White', 'Lake Likesscooters', 'Pippa Middleton', 'Napoleon Bonapart', 'Britany Bartsch', 'Roselee Sabourin', 'Chelsie Vantassel', 'Chaya Daley', 'Luella Cordon', 'Jamel Brekke', 'Jonie Schoemaker', 'Susannah Highfield', 'Mitzi Brouwer', 'Forrest Lazarus', 'Dortha Dacanay', 'Delinda Brouse', 'Alyssa Castenada', 'Carlo Poehler', 'Cicely Rudder', 'Lorraine Galban', 'Trang Lenart', 'Patrica Quirk', 'Zackary Dedios', 'Ursula Kennerly', 'Shameka Flick', 'President Loh', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
//
// randGPS = function(max) {
//   var bottomLng, leftLat, randCoordinates, randLat, randLng, rightLat, skew, topLng;
//   leftLat = 38.994052;
//   rightLat = 38.981376;
//   bottomLng = -76.936569;
//   topLng = -76.950603;
//   skew = 1000000;
//   randLat = [];
//   randLng = [];
//   _.times(max, function() {
//     randLat.push(_.random(leftLat * skew, rightLat * skew) / skew);
//   });
//   _.times(max, function() {
//     randLng.push(_.random(bottomLng * skew, topLng * skew) / skew);
//   });
//   randCoordinates = {
//     lat: randLat,
//     lng: randLng
//   };
//   return randCoordinates;
// };
//
// ref = CurrentDay(), today = ref[0], now = ref[1];
//
// if (DailyBikeData.find({
//   Day: today
// }).count() === 0) {
//   i = 1;
//   while (i <= 200) {
//     Position = [];
//     randomNow = NaN;
//     blank = {};
//     countTime = 0;
//     while (countTime < 30) {
//       randomNow = now - (10000000 * Math.random());
//       namePoint = Math.round((randNames.length - 1) * Math.random());
//       randGPSPoint = Math.round(1 * Math.random());
//       blank = {
//         Rider: randNames[namePoint],
//         Timestamp: randomNow,
//         Lat: randGPS(2).lat[randGPSPoint],
//         Lng: randGPS(2).lng[randGPSPoint]
//       };
//       Position.push(blank);
//       countTime++;
//     }
//     DailyBikeData.insert({
//       Bike: i,
//       Day: today,
//       Tag: Math.round(0.65 * Math.random()) === 0 ? 'Available' : 'RepairInProgress',
//       Positions: Position
//     });
//     i++;
//   }
//   console.log('Created DailyBikeData data schema');
// }
//
// // ---
// // generated by coffee-script 1.9.2
