this.CurrentDay = function() {
  var dateFunc, day, diff, oneDay, start;
  dateFunc = new Date;
  start = new Date(dateFunc.getFullYear(), 0, 0);
  diff = dateFunc - start;
  oneDay = 1000 * 60 * 60 * 24;
  day = Math.floor(diff / oneDay);
  return [day, dateFunc.getTime()];
};

// ---
// generated by coffee-script 1.9.2
